services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: hello
      POSTGRES_USER: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: postgres://root:hello@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
  app:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: .
  #     target: dev
    restart: always
  #   develop:
  #     watch:
  #       - path: ./drizzle.config.ts
  #         target: /app/drizzle.config.ts
  #         action: sync
  #       - path: ./package.json
  #         action: rebuild
  #       - path: ./app
  #         target: /app/app
  #         action: sync
  #       - path: ./db
  #         target: /app/db
  #         action: sync+restart
  #       - path: ./components
  #         target: /app/components
  #         action: sync
  #       - path: ./lib
  #         target: /app/lib
  #         action: sync
  #       - path: ./public
  #         target: /app/public
  #         action: sync
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://root:hello@db:5432/mydb
      SECRET: your_secret_key_here
  #   volumes:
  #     - node_modules:/app/node_modules
volumes:
  db_data1:
  # node_modules:
